import json
import pandas as pd
import random

DEFAULT_SYSTEM_PROMPT = 'You are a AI detection assistant for Machine Learning. You should help the user to detect whether the writing is created by AI according to the wording and writting habit of AI.'

def create_dataset(question, answer):
    return {
        "messages": [
            {"role": "system", "content": DEFAULT_SYSTEM_PROMPT},
            {"role": "user", "content": question},
            {"role": "assistant", "content": answer},
        ]
    }

if __name__ == "__main__":
    df = pd.read_csv("testing500.csv")
    #pre_df = df["human"]
    with open("train.jsonl", "w") as f:
        for _, row in df.iterrows():
            example_str = json.dumps(create_dataset(row["AI"], "This message is generated by AI"))
            f.write(example_str + "\n")
    with open("train.jsonl", "a") as f:
        for _, row in df.iterrows():
            example_str = json.dumps(create_dataset(row["human"], "This message is written by Human"))
            f.write(example_str + "\n")


    input_file = '/home/ubuntu/xchange/openai/train.jsonl'
    train_file = '/home/ubuntu/xchange/openai/train_train.jsonl'
    validate_file = '/home/ubuntu/xchange/openai/train_validate.jsonl'
    test_file = '/home/ubuntu/xchange/openai/train_test.jsonl'

    # Read the JSONL file
    data = []
    with open(input_file, 'r') as f:
        lines = f.readlines()  # Read all lines into a list
        random.shuffle(lines)  # Shuffle the order of the lines

        for line in lines:
            data.append(json.loads(line))

    # Split the data
    split_index = int(0.1 * len(data))
    split_index2 = int(0.7 * len(data))

    test_data = data[:split_index]
    train_data = data[split_index:split_index2]
    validate_data = data[split_index2:]

    # Write the training data to a new JSONL file
    with open(train_file, 'w') as f:
        for item in train_data:
            f.write(json.dumps(item) + '\n')

    # Write the testing data to a new JSONL file
    with open(test_file, 'w') as f:
        for item in test_data:
            f.write(json.dumps(item) + '\n')

    with open(validate_file, 'w') as f:
        for item in validate_data:
            f.write(json.dumps(item) + '\n')

    print("Data split into training and testing sets.")